version: '2'
services:
  projetwebecoleprimaire-app:
    image: projetwebecoleprimaire
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://projetwebecoleprimaire-mysql:3306/projetwebecoleprimaire?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  projetwebecoleprimaire-mysql:
    extends:
      file: mysql.yml
      service: projetwebecoleprimaire-mysql
